import { describe, it, expect } from "vitest";
import { deriveClientKeys, deriveServerKeys } from "../key-exchange";
import { generateKeypair } from "../keypair";
import sodium from "libsodium-wrappers-sumo";

describe("key-exchange", () => {
  it("deriveClientKeys returns {rx, tx} Uint8Arrays of length 32", async () => {
    const alice = await generateKeypair();
    const bob = await generateKeypair();
    const keys = await deriveClientKeys(alice.publicKey, alice.secretKey, bob.publicKey);
    expect(keys.rx).toBeInstanceOf(Uint8Array);
    expect(keys.tx).toBeInstanceOf(Uint8Array);
    expect(keys.rx.length).toBe(32);
    expect(keys.tx.length).toBe(32);
  });

  it("deriveServerKeys returns {rx, tx} Uint8Arrays of length 32", async () => {
    const alice = await generateKeypair();
    const bob = await generateKeypair();
    const keys = await deriveServerKeys(bob.publicKey, bob.secretKey, alice.publicKey);
    expect(keys.rx).toBeInstanceOf(Uint8Array);
    expect(keys.tx).toBeInstanceOf(Uint8Array);
    expect(keys.rx.length).toBe(32);
    expect(keys.tx.length).toBe(32);
  });

  it("clientKeys.tx === serverKeys.rx and clientKeys.rx === serverKeys.tx (directional symmetry)", async () => {
    const alice = await generateKeypair();
    const bob = await generateKeypair();

    // Alice is the initiator (client role), Bob is the responder (server role)
    const clientKeys = await deriveClientKeys(alice.publicKey, alice.secretKey, bob.publicKey);
    const serverKeys = await deriveServerKeys(bob.publicKey, bob.secretKey, alice.publicKey);

    // Client's tx key should equal server's rx key
    expect(Buffer.from(clientKeys.tx)).toEqual(Buffer.from(serverKeys.rx));
    // Client's rx key should equal server's tx key
    expect(Buffer.from(clientKeys.rx)).toEqual(Buffer.from(serverKeys.tx));
  });

  it("message encrypted with clientKeys.tx can be decrypted with serverKeys.rx", async () => {
    await sodium.ready;
    const alice = await generateKeypair();
    const bob = await generateKeypair();

    const clientKeys = await deriveClientKeys(alice.publicKey, alice.secretKey, bob.publicKey);
    const serverKeys = await deriveServerKeys(bob.publicKey, bob.secretKey, alice.publicKey);

    // Alice encrypts with her tx key
    const plaintext = sodium.from_string("Bonjour, je vous contacte pour mon dossier");
    const nonce = sodium.randombytes_buf(sodium.crypto_secretbox_NONCEBYTES);
    const ciphertext = sodium.crypto_secretbox_easy(plaintext, nonce, clientKeys.tx);

    // Bob decrypts with his rx key
    const decrypted = sodium.crypto_secretbox_open_easy(ciphertext, nonce, serverKeys.rx);
    expect(sodium.to_string(decrypted)).toBe("Bonjour, je vous contacte pour mon dossier");
  });

  it("works with keypairs generated by existing generateKeypair()", async () => {
    await sodium.ready;
    const kp1 = await generateKeypair();
    const kp2 = await generateKeypair();

    // Verify the keypairs are crypto_box compatible (X25519)
    expect(kp1.publicKey.length).toBe(sodium.crypto_box_PUBLICKEYBYTES);
    expect(kp1.secretKey.length).toBe(sodium.crypto_box_SECRETKEYBYTES);

    // Key exchange should work without errors
    const clientKeys = await deriveClientKeys(kp1.publicKey, kp1.secretKey, kp2.publicKey);
    const serverKeys = await deriveServerKeys(kp2.publicKey, kp2.secretKey, kp1.publicKey);

    // Bidirectional: encrypt with server tx, decrypt with client rx
    const msg = sodium.from_string("Reply from lawyer");
    const nonce = sodium.randombytes_buf(sodium.crypto_secretbox_NONCEBYTES);
    const ciphertext = sodium.crypto_secretbox_easy(msg, nonce, serverKeys.tx);
    const decrypted = sodium.crypto_secretbox_open_easy(ciphertext, nonce, clientKeys.rx);
    expect(sodium.to_string(decrypted)).toBe("Reply from lawyer");
  });
});
